name: "Run ComfyUI on Various OSs"
description: "Run a comfyui workflow on various OSs - uv + GitHub Artifacts version"
inputs:
  os:
    description: "Operating System. macos, linux, windows."
    required: true
    default: ""
  python_version:
    description: "Python Version."
    required: false
    default: "3.11"
  cuda_version:
    description: "CUDA Version."
    required: false
    default: "12.1"
  torch_version:
    description: "Pytorch Version type, 'stable', 'nightly', 'specific'"
    required: false
    default: 'stable'
  specific_torch_install:
    description: "Command for installing specific torch version."
    required: false
    default: ''
  models-json:
    description: 'JSON string containing models and their download URLs.'
    required: false
  workflow_filenames:
    description: "The list of workflow filenames. Separate by comma."
    required: false
    default: 'auto'
  comfyui_flags:
    description: "Flags to pass to the comfyui application."
    required: false
    default: ''
  use_prior_commit:
    description: "Specify 'true' to use the prior commit."
    required: false
    default: 'false'
  timeout:
    description: "Timeout for the workflow (in seconds)"
    required: false
    default: "600"
  skip_quickci:
    description: "Skip quickci."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: '[Universal] Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    ############################################################
    ##                      Unix Steps                        ##
    ############################################################
    - name: '[Unix] Setup uv'
      if: ${{ inputs.os != 'windows' }}
      uses: astral-sh/setup-uv@v4

    - name: '[Unix] Setup Python'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        uv python install ${{ inputs.python_version }}
        uv python pin ${{ inputs.python_version }}

    - name: '[Unix] Install Pytorch stable'
      if: ${{ inputs.os == 'linux' && inputs.torch_version == 'stable' }}
      shell: bash -el {0}
      run: |
        uv pip install torch torchvision torchaudio --system --index-url https://download.pytorch.org/whl/cu121

    - name: '[Unix] Install Pytorch nightly'
      if: ${{ inputs.os == 'linux' && inputs.torch_version == 'nightly' }}
      shell: bash -el {0}
      run: |
        uv pip install --pre torch torchvision torchaudio --system --index-url https://download.pytorch.org/whl/nightly/cu121

    - name: '[Unix] Install Pytorch stable (macOS)'
      if: ${{ inputs.os == 'macos' && inputs.torch_version == 'stable' }}
      shell: bash -el {0}
      run: |
        uv pip install torch torchvision torchaudio --system

    - name: '[Unix] Install Pytorch nightly (macOS)'
      if: ${{ inputs.os == 'macos' && inputs.torch_version == 'nightly' }}
      shell: bash -el {0}
      run: |
        uv pip install --pre torch torchvision torchaudio --system --index-url https://download.pytorch.org/whl/nightly

    - name: '[Unix] Install Pytorch specific version'
      if: ${{ inputs.os != 'windows' && inputs.torch_version == 'specific' }}
      shell: bash -el {0}
      run: |
        echo "Run specific torch install command"
        ${{ inputs.specific_torch_install }}

    - name: '[Unix] Install dependencies'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        uv pip install -r requirements.txt --system
        uv pip install -U comfy-cli --system

    - name: '[Unix] Check environment'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        which python
        echo "#### Python Version ####"
        python --version
        echo "#### Pip Version ####"
        pip --version
        echo "#### uv Version ####"
        uv --version

    - name: '[Unix] Download models'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        cd ${{ github.action_path }}
        uv pip install -r requirements.txt --system
        echo "will run default-models prep"
        python default-models-prep.py --cache-directory ~/.cache/comfy-actions-runner/modelcache --live-directory "$GITHUB_WORKSPACE/models"
        echo "default-models-prep done, will copy workflow images"
        cp -r "${{ github.action_path }}"/workflow-images/* "$GITHUB_WORKSPACE/input" 2>/dev/null || true
        echo "workflow images copied"

    - name: '[Unix] Run ComfyUI quick test'
      if: ${{ inputs.os != 'windows' && inputs.skip_quickci != 'true' }}
      shell: bash -el {0}
      run: |
        python main.py --quick-test-for-ci

    - name: '[Unix] Run ComfyUI'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        python main.py ${{ inputs.comfyui_flags }} > application.log 2>&1 &

    - name: '[Unix] Check if the server is running'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        cd ${{ github.action_path }}
        python poll_server_start.py > application.log 2>&1

    - name: '[Unix] Run Python Action'
      id: unix_action
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        if [ "${{ inputs.use_prior_commit }}" == "true" ]; then
          COMMIT_HASH=$(git rev-parse HEAD^)
        else
          COMMIT_HASH=$(git rev-parse HEAD)
        fi
        BRANCH_NAME="${{ github.ref_name }}"
        PRNUMBER="${{ github.event.pull_request.number }}"
        if [ -n "$PRNUMBER" ]; then
          BRANCH_NAME="$PRNUMBER/merge"
          git fetch origin pull/$PRNUMBER/head
          git checkout FETCH_HEAD
          COMMIT_HASH=$(git rev-parse HEAD)
        fi
        TIMESTAMP=$(git show -s --format=%cI $COMMIT_HASH)
        MESSAGE=$(git show -s --format=%s $COMMIT_HASH)

        cd ${{ github.action_path }}
        echo "Running workflows: ${{ inputs.workflow_filenames }}"
        python action.py \
          --comfy-workflow-names ${{ inputs.workflow_filenames }} \
          --github-action-workflow-name "${{ github.workflow }}" \
          --os "${{ inputs.os }}" \
          --run-id "${{ github.run_id }}" \
          --job-id "${{ github.job }}" \
          --job-trigger-user "${{ github.actor }}" \
          --workspace-path "${{ github.workspace }}" \
          --output-file-prefix "ComfyUI" \
          --repo "${{ github.repository }}" \
          --comfy-run-flags "'${{ inputs.comfyui_flags }}'" \
          --python-version "${{ inputs.python_version }}" \
          --torch-version "${{ inputs.torch_version }}" \
          --cuda-version "${{ inputs.cuda_version }}" \
          --commit-hash "$COMMIT_HASH" \
          --commit-time "$TIMESTAMP" \
          --commit-message "$MESSAGE" \
          --branch-name "$BRANCH_NAME" \
          --api-endpoint "https://api.comfy.org/upload-artifact"

    - name: '[Unix] Upload Output Files'
      uses: actions/upload-artifact@v4
      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
      with:
        name: output-files-${{ github.job }}-${{ inputs.os }}-${{ inputs.python_version }}-${{ inputs.cuda_version }}-${{ inputs.torch_version }}-run${{ github.run_id }}
        path: ${{ github.workspace }}/output/**

    - name: '[Unix] Upload log file'
      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
      uses: actions/upload-artifact@v4
      with:
        name: app-logs-${{ github.job }}-${{ inputs.os }}-${{ inputs.python_version }}-${{ inputs.cuda_version }}-${{ inputs.torch_version }}-run${{ github.run_id }}
        path: ${{ github.workspace }}/application.log

    - name: '[Unix] Cleanup output files only'
      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
      shell: bash -el {0}
      run: rm -rf ${{ github.workspace }}/*

    ############################################################
    ##                      Windows Steps                     ##
    ############################################################
    - name: '[Win] Setup uv'
      if: ${{ inputs.os == 'windows' }}
      uses: astral-sh/setup-uv@v4

    - name: '[Win] Setup Python'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        uv python install ${{ inputs.python_version }}
        uv python pin ${{ inputs.python_version }}

    - name: '[Win] Install Pytorch stable'
      if: ${{ inputs.os == 'windows' && inputs.torch_version == 'stable' }}
      shell: powershell
      run: |
        uv pip install torch torchvision torchaudio --system --index-url https://download.pytorch.org/whl/cu121

    - name: '[Win] Install Pytorch nightly'
      if: ${{ inputs.os == 'windows' && inputs.torch_version == 'nightly' }}
      shell: powershell
      run: |
        uv pip install --pre torch torchvision torchaudio --system --index-url https://download.pytorch.org/whl/nightly/cu121

    - name: '[Win] Install Pytorch specific version'
      if: ${{ inputs.os == 'windows' && inputs.torch_version == 'specific' }}
      shell: powershell
      run: |
        Write-Output "Run specific torch install command"
        ${{ inputs.specific_torch_install }}

    - name: '[Win] Install dependencies'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        uv pip install -r requirements.txt --system
        uv pip install -U comfy-cli --system

    - name: '[Win] Check environment'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        Get-Command python
        Write-Output "#### Python Version ####"
        python --version
        Write-Output "#### Pip Version ####"
        pip --version
        Write-Output "#### uv Version ####"
        uv --version

    - name: '[Win] Download models'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        cd $Env:GITHUB_ACTION_PATH
        uv pip install -r requirements.txt --system
        python default-models-prep.py --cache-directory C:\actions-runner\modelcache --live-directory "$Env:GITHUB_WORKSPACE/models"
        Copy-Item -Path "$Env:GITHUB_ACTION_PATH\workflow-images\*" -Destination "$Env:GITHUB_WORKSPACE\input" -Recurse -ErrorAction SilentlyContinue

    - name: '[Win] Run ComfyUI quick test'
      if: ${{ inputs.os == 'windows' && inputs.skip_quickci != 'true' }}
      shell: powershell
      run: |
        python $Env:GITHUB_WORKSPACE/main.py --quick-test-for-ci

    - name: '[Win] Run ComfyUI'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        $envGithubWorkspace = $Env:GITHUB_WORKSPACE
        Start-Process powershell -ArgumentList "-File", "${{ github.action_path }}\start-server.ps1", "-GITHUB_WORKSPACE", "`"$envGithubWorkspace`"", "-RunFlags", "`"${{ inputs.comfyui_flags}}`""

    - name: '[Win] Check if the server is running'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        cd $Env:GITHUB_ACTION_PATH
        python poll_server_start.py

    - name: '[Win] Run Python Action'
      id: windows_action
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        if ( "${{ inputs.use_prior_commit }}" -eq "true" ) {
          $commit_hash = git rev-parse HEAD^
        } else {
          $commit_hash = git rev-parse HEAD
        }
        $branch_name = "${{ github.ref_name }}"
        $pr_number = "${{ github.event.pull_request.number }}"
        if ( $pr_number -ne "" ) {
          $branch_name = "$pr_number/merge"
          git fetch origin pull/$pr_number/head
          git checkout FETCH_HEAD
          $commit_hash = git rev-parse HEAD
        }
        $timestamp = git show -s --format=%cI $commit_hash
        $message = git show -s --format=%s $commit_hash

        $branch_name = $branch_name -replace '"', '\"'
        $message = $message -replace '"', '\"'
        $actor = "${{ github.actor }}"
        $actor = $actor -replace '"', '\"'

        cd $Env:GITHUB_ACTION_PATH
        Write-Host "Running workflows: ${{ inputs.workflow_filenames }}"
        python action.py `
          --comfy-workflow-names "${{ inputs.workflow_filenames }}" `
          --github-action-workflow-name "${{ github.workflow }}" `
          --os "${{ inputs.os }}" `
          --run-id "${{ github.run_id }}" `
          --job-id "${{ github.job }}" `
          --job-trigger-user $actor `
          --workspace-path "${{ github.workspace }}" `
          --output-file-prefix "ComfyUI" `
          --repo "${{ github.repository }}" `
          --comfy-run-flags "'${{ inputs.comfyui_flags }}'" `
          --python-version "${{ inputs.python_version }}" `
          --torch-version "${{ inputs.torch_version }}" `
          --cuda-version "${{ inputs.cuda_version }}" `
          --commit-hash "$commit_hash" `
          --commit-time "$timestamp" `
          --commit-message $message `
          --branch-name $branch_name `
          --api-endpoint "https://api.comfy.org/upload-artifact"

    - name: '[Win] Upload Output Files'
      uses: actions/upload-artifact@v4
      if: ${{ inputs.os == 'windows' && ( success() || failure() ) }}
      with:
        name: output-files-${{ github.job }}-${{ inputs.os }}-${{ inputs.python_version }}-${{ inputs.cuda_version }}-${{ inputs.torch_version }}-run${{ github.run_id }}
        path: ${{ github.workspace }}/output/**

    - name: '[Win] Upload log file'
      uses: actions/upload-artifact@v4
      if: ${{ inputs.os == 'windows' && ( success() || failure() ) }}
      with:
        name: app-logs-${{ github.job }}-${{ inputs.os }}-${{ inputs.python_version }}-${{ inputs.cuda_version }}-${{ inputs.torch_version }}-run${{ github.run_id }}
        path: ${{ github.workspace }}/application.log

    - name: '[Win] Cleanup output files only'
      if: ${{ inputs.os == 'windows' && ( success() || failure() ) }}
      shell: powershell
      run: Remove-Item -Path "${{ github.workspace }}/output/*" -Recurse -Force -ErrorAction SilentlyContinue
